      - name: Instagramga joylash
        env:
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        run: |
          echo "=== INSTAGRAMGA JOYLASH ==="
          pip install instagrapi==2.1.1
          python upload_and_post.py
